name: Fuzz

on: 
  push:
    branches: 
      - 'main'

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push
      run: docker build -t dockertest
    - name: run 
      run: docker run dockertest
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: workspace_artifacts
        path: ${{ github.workspace }}
