name: Fuzz

on: 
  push:
    branches: 
      - 'main'

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push
      run: docker build . --file Dockerfile
    - name: Run Docker file
      run: docker run
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: workspace_artifacts
        path: ${{ github.workspace }}
