name: Fuzz

on: 
  push:
    branches: 
      - 'main'

    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v4
    - name: Build and push
      run: docker build . --file Dockerfile
