name: Fuzz

on: 
  push:
    branches: 
      - 'main'

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Buildx
      run: |
        docker buildx build -f Dockerfile --output . .
 
    - name: Check
      run: |
       ls -la
    - name: Dump docker logs
      uses: jwalton/gh-docker-logs@v2

