name: Fuzz

on: 
  push:
    branches: 
      - 'main'

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build docker images
      run: docker compose build
    - name: Setup database
      run: docker compose run setup
    - name: Run tests
      run: docker compose run test
